---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
env:
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For cosign
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Install Cosign
        uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
        with:
          aqua_version: v1.32.0
      - name: Build
        run: go build -o dist/hello_linux_amd64 ./cmd/hello
      - name: Create checksums.txt
        run: sha256sum hello_linux_amd64 > checksums.txt
        working-directory: dist
      - name: Sign checksums.txt by Cosign
        run: |
          cosign sign-blob \
            --output-certificate=checksums.txt.pem \
            --output-signature checksums.txt.sig \
            --oidc-provider github \
            checksums.txt
        working-directory: dist
        env:
          COSIGN_EXPERIMENTAL: "1"
      - name: Create GitHub Release and upload files
        run: gh release create "${REF#refs/tags/}" checksums.txt checksums.txt.sig checksums.txt.pem hello_linux_amd64
        working-directory: dist
        env:
          REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ github.token }}
